Разметка главной страницы
htmlacademy-htmlcss/1083949-sedona-33 pull request #2
Opened 2022-01-21 17:23 UTC by olgabelka81

2022-01-22 10:20 UTC, ego-o requested changes
В целом, с разметкой у нас не плохо :) 

Видно, что  есть опыт и в стилизации,так как во многих местах были добавленны контейнеры на будущее. Но пка данные контейнеры нужно убрать, так как во первых: сейчас определить смысл их назначения, не видя самих стилей; а во вторых, чем меньше в HTML элементов, тем проще нам читать код, а браузеру парсить сраницу.

Еще немного поторопилась с графикой, сейчас её экспортировать не надо, это тема следующего занятия. Давай их пока удалим и зафиксируем отдельным коммитом. Там просто есть ошибки в именовании файлов, которые немного сложно исправлять, с ними разберемся чуть позже.

Но опыт в верстке у тебя заметен) Хоть замечаний оставил и много, они все по мелочам, так что молодец)

2022-01-22 10:20 UTC, saranchyev commented on index.html
> +        <div class="container">
Данный контейнер является лишним. Сейчас в нем нет необходимости, и он не несет никакой смысловой нагрузки
https://up.htmlacademy.ru/htmlcss/33/criteries#HTML-06

2022-01-22 10:20 UTC, saranchyev commented on index.html
> +              </span>
Как я пониммаю, `<span class="favorite">` был добавлен для того, чтобы вставить в него иконку избранного. Но иконку нужно будет вставлять внутрь самой ссылки, а не за её пределами, поэтому данный `span` лишний.

2022-01-22 10:20 UTC, saranchyev commented on index.html
> +              <a href="#" class="main-nav-link user-nav-link">Избранное</a>
Текст внутри ссылки должен быть обернут в `span` с классом `visually-hidden`, так как он в последствии будет скрыт

2022-01-22 10:20 UTC, saranchyev commented on index.html
> +        <div class="container">
У тега `section` обязательно дожен быть заголовок, который описывает контент внути него - т.е. "Приемущества". Но так как на дизайне заголовка нет, то добавляем его и делаем скрытым.

В теге div с классом `container` тоже пока нет никакой необходимости

2022-01-22 10:20 UTC, saranchyev commented on index.html
> +            <img class="main-nav-logo-img logo-img" src="img/logo.svg" width="139" height="70" alt="Логотип Sedona">
В аттрибуте alt, в конце текстовго описания должна стоять точка 
https://up.htmlacademy.ru/htmlcss/33/criteries#ALLY-01

2022-01-22 10:20 UTC, saranchyev commented on index.html
> +          <img class="promo-img-inscription" src="img/welcome.svg" width="458" height="352" alt="Приветственная надпись">
В аттрибуте alt, в конце текстовго описания должна стоять точка 
https://up.htmlacademy.ru/htmlcss/33/criteries#ALLY-01

2022-01-22 10:20 UTC, saranchyev commented on index.html
> +                  своя жизнь</p>
Туту очень странное форматирование кода. У текста "Настоящий городок" не нужно делать перенос строки, он все равно не перенесется бразуером как на макете без тега <br> или сжатия контейнера (к этому мы прийдем потом). А вот читаемость кода такие переносы портят. И далее текст вместе с тегаи по какой-то причине начинает смещаться вправо, как будто `span` вложен в `h3`. Это только запутывает

Так что нужно убрать все эти переносы текста в коде. Это же касается и блоков ниже

2022-01-22 10:20 UTC, saranchyev commented on index.html
> +                <span class="counter"></span>
span пока является личшним элементом, не содержащим никакой смысловой нагрузки
https://up.htmlacademy.ru/htmlcss/33/criteries#HTML-06

2022-01-22 10:20 UTC, saranchyev commented on index.html
> +          <aside class="privilege-aside">
Да, это не отдельный блок. Это на самом деле еще один дополнительный список, который относится к первому приеуществу. Он как бы раскрывает, почему седону можно считать настоящим городком.

Поэтму тег `aside` подобран неудачно. `aside` это какая-либо боковая область сайта, не его переферии. Допустим, с дополнительным меню, последнии статьями из блога, рекламой, и прочим, что нельзя отнести к шапке или подвалу сайта, навигации и основному контенту страницы

2022-01-22 10:20 UTC, saranchyev commented on index.html
> +          <h3 class="search-hostel-title">Заинтересовались?</h3>
Здесь правильнее по структуре должен быть не h3, а h2

```
h1 Седона
    h2 Седона — небольшой городок в Аризоне, заслуживающий большего!
    h2 Приемущества
        h3 Настоящий городок
        h3 Там есть мост дьявола
        h3 Небольшая площадь
        h3 Красивая дорога
        h3 Мало туристов
    h2 Заинтересовались?
    h2 Подпишитесь на рассылку
```

2022-01-22 10:20 UTC, saranchyev commented on index.html
> +          <h3 class="mailling-title">Подпишитесь на рассылку</h3>
Здесь тоже самое, h2

2022-01-22 10:20 UTC, saranchyev commented on index.html
> +          <form class="mailling-subscribe" action="#" method="post">
Для форм в аттриут `action` указываем следующий адрес, чтобы можно было проверять их работоспособность - https://echo.htmlacademy.ru

2022-01-22 10:20 UTC, saranchyev commented on index.html
> +    <article class="modal-okno">
На данном этапе пока не нужно размечать модальные окна, так что его разметку удаляем.

Так же по именованию классов - слово `okno` недопустио, так как является транслитом
https://up.htmlacademy.ru/htmlcss/33/criteries#PROJ-02

2022-01-22 10:20 UTC, saranchyev commented on catalog.html
> +            <img class="main-nav-logo-img logo-img" src="img/logo.svg" width="139" height="70" alt="Логотип Sedona">
В аттрибуте alt, в конце текстовго описания должна стоять точка
https://up.htmlacademy.ru/htmlcss/33/criteries#ALLY-01

2022-01-22 10:20 UTC, ego-o commented on catalog.html
> +            <img class="footer-logo-img" src="img/logo-footer.svg" width="115" height="33" alt=".htmlacademy">
В аттрибуте alt, в конце текстовго описания должна стоять точка
https://up.htmlacademy.ru/htmlcss/33/criteries#ALLY-01

Текстовое описание не раскрывает сути изображения. Нужно добавить чуть больше смысла, например "разработано в htmlacademy"

2022-01-22 10:20 UTC, ego-o commented on catalog.html
> +          <h3 class="mailling-title">Подпишитесь на рассылку</h3>
Тут должно быть h2

2022-01-22 10:20 UTC, ego-o commented on catalog.html
> +          <form class="mailling-subscribe" action="#" method="post">
форма должна ссылаться на https://echo.htmlacademy.ru

2022-01-22 10:20 UTC, ego-o commented on catalog.html
> +            <a class="socials-link socials-link-twitter" href="https://twitter.com/htmlacademy_ru"><span class="visually-hidden">Twitter</span></a>
Тут неверное форатирование. Каждый вложенный тег должен быть с новой строки
https://up.htmlacademy.ru/htmlcss/33/criteries#PROJ-01

2022-01-22 10:20 UTC, ego-o commented on catalog.html
> +              <a href="#" class="main-nav-link user-nav-link">Избранное</a>
`span` с классом `favorite` на данном этапе лишний. Текст внутри ссылок должен быть обернут в `span` с классом `visually-hidden`. Аналогично и у блоков ниже по коду

2022-01-22 10:20 UTC, ego-o commented on index.html
> +            <a class="socials-link socials-link-twitter" href="https://twitter.com/htmlacademy_ru"><span class="visually-hidden">Twitter</span></a>
Тут неверное форматирование. Каждый вложенный тег должен быть с новой строки
https://up.htmlacademy.ru/htmlcss/33/criteries#PROJ-01

2022-01-22 10:55 UTC, olgabelka81 commented on index.html
> +                  своя жизнь</p>
На самом деле не заметила, так фраза скопировалась из макета. Поправлю.

2022-01-22 11:04 UTC, olgabelka81 commented on index.html
> +          <aside class="privilege-aside">
Поняла, спасибо.

2022-01-22 17:15 UTC, ego-o requested changes
Все исправлено, молодец) Немного корректировок еще есть, но с ними ты быстро справишься)

2022-01-22 17:15 UTC, saranchyev commented on index.html
> +                <h3 class="privilege-aside-title">Жильё</h3>
Для списка причин, почему седона является настоящим городком, не очень подходит h3. Заголовки у нас получаются выстраиваются в один уровень с остальными причинами:

- Настоящий городок
- Жильё
- Еда
- Сувениры
- Там есть мост дъявола

Хотя должно быть так:
- Настоящий городок
    - Жильё
    - Еда
    - Сувениры
- Там есть мост дъявола

Т.е. заголовок нужно или поменять на h4, или не делать его загголовком вовсе, обернув его, например, в `<strong>`.

2022-01-22 17:15 UTC, saranchyev commented on index.html
> +        <a href="https://htmlacademy.ru" class="main-nav-logo logo">
Аттрибут `class` должен вседа идти после имени тега. Перепроверь это по всей странице, пожалуйста, есть еще такие места

https://up.htmlacademy.ru/htmlcss/33/criteries#PROJ-01
http://codeguide.academy/html-css.html#html-attr-order

2022-01-22 17:15 UTC, saranchyev commented on index.html
> +            ><span class="visually-hidden">Youtube</span></a>
Закрывающая кавычка `>` убежала не на ту строчку

2022-01-22 17:15 UTC, saranchyev commented on index.html
> +            <span class="visually-hidden">Facebook</span></a>
Закрывающий тег `<a>` нужно перенести на новую строку

2022-01-22 17:15 UTC, saranchyev commented on catalog.html
> +        <h3 class="sorting-title">Найдено гостиниц: 38</h3>
"Найдено гостиниц" не является заголовком. Этот текст просто выглядит крупным, но он не озаглавливает никакой раздел и не отвечает на вопрос, что содержится в этой секции

2022-01-22 17:15 UTC, saranchyev commented on catalog.html
> +          <span class="visually-hidden">Показать карточки</span>
Тут стоить немного уточнить текст. В "показать карточки" не очень понятно, какие карточки будут показаны, если нажать на данную ссылку. Лучше уточнить, что они для изменения внешнего вида найденых гостиниц

- "Отображать гостиницы плиткой"
- "Отображать гостиницы карточками"
- "Отображать гостиницы списком"

2022-01-22 17:15 UTC, saranchyev commented on catalog.html
> +              <h3 class="sorting-card-title">Amara Resort & Spa</h3>
Заголовок лучше разместить первым. Если вдруг на сайте по каким-то причинам не зарузятся стили, страница все равно должна остаться читаемой. Просто она будет похожа на документ Microsoft Word. И она будет лучше смотреться и читаться, если сначала у нас будет заголовок с названием гостинцы, а потом уже её фоторафия. Когда будем стилизовать мы можем картинку с заголовком поменять местами.

А в текущем варианте прийдется еще немного потратить времени, чтобы понять, к какой гостинице относится та или иная фоторафия.

2022-01-22 17:15 UTC, ego-o commented on catalog.html
> +        <h2 class="visually-hidden">Сортировка</h2>
Текущий вариант заоловка секции не вяжется с её содержимым - секция озаглавлена как сортировка, но содержит и сортировку, и список гостиниц - https://skr.sh/sC8WIApi7l6

Нужно либо переименовать заголовок, чтобы он соответствовал содержимому секции, либо выделить список гостиниц в отдельную секцию

2022-01-22 17:15 UTC, ego-o commented on catalog.html
> +            <button class="btn-favourites" type="button">В избранное</button>
"В избранное" тоже лучше сделать ссылкой. Так как это сейчас кнопка, заставить её работать можно только через JS. И в случае, если у пользователя не будет работать JS, то добавить товар в избранное не получится. А если это будет ссылка, то перейдя по ней отработает скрипт на стороне сервера, и гостиница будет добавлена в избранное.

JS же, как и стили, может не загрузиться по разным причинам. Например, медленный интернет, проблемы на сервере где лежит сайт, блокировщики рекламы, и так далее. Да, это не частые кейсы, но они все же случаются. И важно, чтобы критический функционал сайта все равно оставался в рабочем состоянии

2022-01-22 17:15 UTC, ego-o commented on catalog.html
> +        <button class="button pagination-show-more" type="button">Загрузить ещё</button>
А здесь будет кнопка, тут все правильно 👍. Функционал "Загрузить еще" можно сделать только через JS

2022-01-22 17:15 UTC, ego-o commented on catalog.html
> +          <label class="count" for="count-input">Гостиниц на странице:
Текст "Гостиниц на странице" следует так же перенести на новую строку

2022-01-22 17:24 UTC, merged

2022-01-23 11:26 UTC, olgabelka81 commented on catalog.html
> +        <h2 class="visually-hidden">Сортировка</h2>
Выделила список гостиниц в отдельную <section class="catalog">

2022-01-23 11:39 UTC, olgabelka81 commented on catalog.html
> +            <button class="btn-favourites" type="button">В избранное</button>
Здесь, я как раз долго думала, что выбрать, но в конечном итоге решила: раз мы никуда не переходим, то всё-таки копка.