Графика для всех страниц
htmlacademy-htmlcss/1083949-sedona-33 pull request #4
Opened 2022-01-30 16:40 UTC by olgabelka81

2022-01-31 10:28 UTC, ego-o requested changes
https://skr.sh/sCH1zFCh9n4
Для изображений гостиниц лучше создать еще одну папку, например `images/catalog`, и разместить их там. Соответсвенно, из имени файлов можно будет убрать слово `catalog`, чтобы его не дублировать

------

https://skr.sh/sCHoVIFXPmK
Для иконок так же лучше создать еще одну папку `images/icons`, и перенести все иконки в неё

-----

https://skr.sh/sCH0Emuijtl
Данные изображения так же можно сгруппировать в отдельную папку по смыслу - `images/reasons`, так как они все используются в блоке с причинамми, почему седона настоящий городок

2022-01-31 10:28 UTC, ego-o commented on catalog.html
> +              <img class="catalog-img" src="images/catalog-hotel-1.png" width="299" height="220" alt="Фото гостиницы Amara Resort & Spa.">
Для фото гостиниц лучше подойдет именно jpeg, чем png. Почему решила сделать именно в png?

2022-01-31 10:28 UTC, ego-o commented on images/stars.svg
> +<svg width="91" height="17" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="m9 0 2.1 6.5H18l-5.6 4 2.2 6.5L9 13l-5.6 4 2.2-6.5-5.6-4h6.9L9 0ZM34 0l2.1 6.5H43l-5.6 4 2.2 6.5-5.6-4-5.6 4 2.2-6.
Тут либо нужно экспортировать только одну звездочку, либо все 5.
Т.е. когда будем выводить рейтинг у гостиниц, мы
- Либо будем вставлять столько звездочек, сколько нужно
- Либо будем скрывать лишние звездочки, путем уменьшения ширины у картинки

Как сделать блок с рейтингом при помощи картинки, у которой 4 звездочки (как сейчас) мне пока не понятно

2022-01-31 10:28 UTC, ego-o commented on index.html
> +        <img class="promo-img-inscription" src="images/welcome.svg" width="458" height="352" alt="Приветственная надпись."/>
С одной стороны да, можно через background.
С другой стороны это изображение помогает понять, а как же выглядит эта седона, красиво ли здесь и стоит ли сюда ехать.
Поэтому, я больше за то, что это контентное изображение

2022-02-01 05:37 UTC, olgabelka81 commented on catalog.html
> +              <img class="catalog-img" src="images/catalog-hotel-1.png" width="299" height="220" alt="Фото гостиницы Amara Resort & Spa.">
С лайва, поняла, что надо именно png... Поправлю.

2022-02-01 05:38 UTC, olgabelka81 commented on images/stars.svg
> +<svg width="91" height="17" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="m9 0 2.1 6.5H18l-5.6 4 2.2 6.5L9 13l-5.6 4 2.2-6.5-5.6-4h6.9L9 0ZM34 0l2.1 6.5H43l-5.6 4 2.2 6.5-5.6-4-5.6 4 2.2-6.
Тут, я не заметила, что максимум пять звёзд.

2022-02-01 05:56 UTC, ego-o commented on catalog.html
> +              <img class="catalog-img" src="images/catalog-hotel-1.png" width="299" height="220" alt="Фото гостиницы Amara Resort & Spa.">
В большинстве случаев фотографии лучше всего сохранять именно в `jpeg`, так как у него лучше сжатие и изображение меньше весит, чем `png`. В `png` экспорт делается обычно только тогда, когда изображение является растровым и содержит прозрачный фон.

2022-02-01 06:08 UTC, olgabelka81 commented on catalog.html
> +              <img class="catalog-img" src="images/catalog-hotel-1.png" width="299" height="220" alt="Фото гостиницы Amara Resort & Spa.">
С лайва поняла, что надо png, если потом добавится другой формат, карточки не сломаются... Поправлю.

2022-02-01 17:21 UTC, merged