Базовая стилизация всех страниц
htmlacademy-htmlcss/1083949-sedona-33 pull request #5
Opened 2022-02-03 10:01 UTC by olgabelka81

2022-02-03 13:58 UTC, ego-o requested changes
В css множество раз используется оди и те же цвета. Их лучше всего вынести в кастомные свойства. Будет проще изменить цвет в одном месте, чем выполнять поиск и замену по всему файлу.
https://tproger.ru/articles/custom-properties-in-css-part-1/

---

https://skr.sh/sCKRS09lCMA
https://skr.sh/sCKblBXRZdN
Данные изображения я так же вставил бы через img, так как они помогают пользователю увидеть и оценить достопримечательности

---

https://skr.sh/sCKeWp9gzzE
Фоновый цвет подобран неудачно. Если изображение не загрузится, текст будет невозможно прочитать.

---
https://skr.sh/sCKEfEUChwB
Фоновое изображение должно захватывать и заголовок, иначе белый текст на сером фоне очень плохо читаем. 
фоновый цвет так же подобран неудачно, по этой же причине. Если фоновое изображение не прогрузится, белый текст будет сложно прочитать

---

2022-02-03 13:58 UTC, ego-o commented on styles/style.css
> +  clip:rect(1px, 1px,1px,1px);
В перечислениях, после запятой всегда должен стоять пробел
http://codeguide.academy/html-css.html#css-leading-zero

2022-02-03 13:58 UTC, ego-o commented on styles/style.css
> +  background-color: #7DB54F;
Для записи цвета должны использоваться только строчные буквы 
http://codeguide.academy/html-css.html#css-color-format

2022-02-03 13:58 UTC, ego-o commented on styles/style.css
> +.privilege-list li:nth-child(2) .privilege-item-text {
В селекторах не должно быть вложенности больше двух
https://up.htmlacademy.ru/htmlcss/33/criteries#CSS-03

2022-02-03 13:58 UTC, ego-o commented on styles/style.css
> +  background-color: #83B3D3;
Для записи цвета должны использоваться только строчные буквы 
http://codeguide.academy/html-css.html#css-color-format

2022-02-03 13:58 UTC, ego-o commented on styles/style.css
> +  background-color: #83B3D3;
Для записи цвета должны использоваться только строчные буквы 
http://codeguide.academy/html-css.html#css-color-format

2022-02-03 13:58 UTC, ego-o commented on styles/style.css
> +  background-color: #7DB54F;
Для записи цвета должны использоваться только строчные буквы 
http://codeguide.academy/html-css.html#css-color-format

2022-02-03 13:58 UTC, ego-o commented on styles/style.css
> +  background-color: #83B3D3;
Для записи цвета должны использоваться только строчные буквы 
http://codeguide.academy/html-css.html#css-color-format

2022-02-03 15:13 UTC, olgabelka81 commented on styles/style.css
> +.privilege-list li:nth-child(2) .privilege-item-text {
А как здесь поступить лучше? Добавить дополнительный класс первым двум преимуществам?

2022-02-03 16:45 UTC, ego-o commented on styles/style.css
> +.privilege-list li:nth-child(2) .privilege-item-text {
Для li лучше назначить отдельный класс, чтобы получился примерно такой селектор:

```css
.privilege-item:first-child .privilege-item-title { ... }
```

2022-02-04 11:15 UTC, ego-o requested changes
https://skr.sh/sCLZUPZMvof
У данного блока должен быть другой фоновый цвет - https://skr.sh/sCLn5FZfnCB

2022-02-04 11:15 UTC, saranchyev commented on styles/style.css
> +  clip:rect(1px, 1px, 1px, 1px);
Не зватает пробела после :

2022-02-04 11:15 UTC, saranchyev commented on styles/style.css
> +  color: var(--color-dark, #333333);
Второй цвет следует убрать, чтобы было единообразно

2022-02-04 11:15 UTC, ego-o commented on index.html
> +    <link rel="stylesheet" href="styles/style.css" />
Только сейчас заметил - одиночные теги не должны иметь закрывающего слеша. Это необходимо перепроверить на обеих страницах. Касается как мета-тегов, так и изображений
http://codeguide.academy/html-css.html#html-closed-tag

2022-02-04 11:15 UTC, ego-o commented on index.html
> +            <img class="privilege-item-img" src="images/privilege-photo-2.jpg" width="800" height="384" alt="Фото моста дьявола в Седоне.">
https://skr.sh/sCLWREchtCD
синий фон должен быть целиком у всего блока, а не только у заголовка. Цвет шрифта в параграфе должен быть белым

2022-02-04 11:15 UTC, ego-o commented on index.html
> +          <svg class="footer-logo-img" width="115" height="33" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M0 12.9v2.6h2.5v-2.6H0ZM11.6 4.5c-1.6 0-2.8.7-3.6 1.7h-.1V0h-2v15.5h2v-5.3c0-2.1
Я бы добавил самой ссылке aria-label, описывающий куда она ведет, так как у самой ссылки нет текстового описания

2022-02-04 11:31 UTC, olgabelka81 commented on index.html
> +    <link rel="stylesheet" href="styles/style.css" />
Это у меня какой-то плагин так форматировал, я его уже удалила.

2022-02-04 12:02 UTC, merged