Микросетки на флексах для всех страниц
htmlacademy-htmlcss/1083949-sedona-33 pull request #7
Opened 2022-02-11 15:06 UTC by olgabelka81

2022-02-12 07:00 UTC, ego-o requested changes
Уже не плохо! Как поправить логотип у шапки я написал, после этого по ПП уже должно стать лучше. На странице каталога карточки гостиниц пока совсем не по ПП, но это должно быть быстро поправимо.

2022-02-12 07:00 UTC, saranchyev commented on styles/style.css
> +  clip: rect(0 0 0 0);
Значения должны перечисляться через запятую

2022-02-12 07:00 UTC, saranchyev commented on styles/style.css
> +  order: -1;
Для чего добавлен `order: -1`? Логотип и так идет самым первым.

Чтобы нижняя его часть заезжала на следующий блок, логотипу можно выдать абсолютное позиционирование

2022-02-12 07:00 UTC, saranchyev commented on index.html
> +              </a>
https://skr.sh/sCSnUr5iXLs
Тут нужно доработать микросетку

2022-02-12 07:00 UTC, saranchyev commented on styles/style.css
> +  background-image: url("../images/icons/search.svg");
Данные иконки (поиск, избранное) лучше вставлять как inline svg, так как они имеют стили для наведения, клика (смотри стайлайд)

2022-02-12 07:00 UTC, saranchyev commented on styles/style.css
> +  margin-top: -5px;   /*Обрезался логотип, а должен быть сверху картинки */
Тут margin делать отрицательны не нужно. Логотип нужно сделать через абсолютное позиционирование.

---

https://skr.sh/sCSi8UcCOyS
Изображение с текстом нужно отцентрировать
```css
left: 50%;
transform: translateX(-50%);
```

---

https://skr.sh/vCTNPJSidYU?a
Такого происходить не должно. Для этого, изображению с текстом нужно задать, относительно какого элеента страницы будет происходить позиционирование. Т.е. нужно указать `position: relative` контейнеру двух картинок - https://skr.sh/sCTWo1uVi6m

2022-02-12 07:00 UTC, saranchyev commented on styles/style.css
> +  border-radius: 10px;
https://skr.sh/sCSaHeviDtM
Здесь нужно доработать размеры кнопки

2022-02-12 07:00 UTC, saranchyev commented on styles/style.css
> +  background-color: var(--color-white);
https://skr.sh/sCSPMbrIovF
Нужно доработать сетку у форы подписки

2022-02-12 07:00 UTC, saranchyev commented on styles/style.css
> +  padding-bottom: 80px;
https://skr.sh/sCTt9R2rL8N
Нужно так же добавить отсутпы по бокам, чтобы текст не прилепал к его границам

2022-02-12 07:00 UTC, saranchyev commented on index.html
> +                     Рекомендуем пожить в настоящем мотеле, всё как в кино!
https://skr.sh/sCTCAKjZ2kx
Стоит добавить `<br>` в нужных местах, чтобы соответсвовать макету.

---

https://skr.sh/sCTqvIm4su6
Стоит добавить отступы снизу, чтобы текст не прилепал к границе блока

2022-02-12 07:00 UTC, saranchyev commented on styles/style.css
> +  padding: 5px;
https://skr.sh/sCTmafdxxgC
Футер нужно так же доработать по ПП

2022-02-12 07:00 UTC, saranchyev commented on styles/style.css
> +  margin-bottom: 10px;
https://skr.sh/sCTyqOkziU6
Нужно доработать размеры элеентов по ПП.

---

https://skr.sh/sCT196EHoi1
Возможно стоит добавить для всех элементов (или хотя-бы для кнопок) `box-sizing: border-box`, чтобы рамка не влияла на размеры элемента

2022-02-12 07:00 UTC, saranchyev commented on styles/style.css
> +  width: 620px;
https://skr.sh/sCT4Te6VzJ7
Нужно подправить интервал между буквами - `letter-spacing`

2022-02-12 07:00 UTC, saranchyev commented on styles/style.css
> +  margin: 30px 218px;
Чтобы выровнять кнопку по центру, лучше использовать `margin 30px auto`, чтобы расстояние отступов по бокам посчиталось браузером автоматически. Если общий размер страницы увеличится или уменьшится, то не прийдется править margin вручную

2022-02-14 14:09 UTC, olgabelka81 commented on styles/style.css
> +  margin: 30px 218px;
Почему-то не работает...

2022-02-15 08:33 UTC, ego-o requested changes

2022-02-15 08:33 UTC, ego-o commented on styles/style.css
>    display: block;
стоит так же добавить `z-index`, чтобы логотип был поверх изображений, которые идут в блоке ниже

2022-02-15 08:33 UTC, ego-o commented on styles/style.css
> +  height: 60px;
https://skr.sh/sCWamuLHDwR
Шрифт у инпута отличается от макетного (браузер рендерит Arial)

2022-02-15 08:33 UTC, ego-o commented on index.html
> +                <sup class="counter-value">12</sup>
https://skr.sh/sCWCpr9CpL3
Немного не доработана микросетка

2022-02-15 08:33 UTC, ego-o commented on index.html
> +              </div>
https://skr.sh/vCW9wlO32kS?a
Нужно дорабоать отступы снизу у данных блоков при переполнении

2022-02-15 08:33 UTC, ego-o commented on styles/style.css
> +  padding-top: 8px;
Нужно сделать шрифт обычным, убрать курсив

2022-02-15 08:33 UTC, ego-o commented on styles/style.css
> +  margin-bottom: 10px;
https://skr.sh/sCWoUdnxcXC
Нужно доработать размеры карточек гостиниц по ПП

2022-02-15 08:33 UTC, ego-o commented on styles/style.css
> +  left: 50%;
https://skr.sh/sCWPyfln5td
margin работает, нужно было только еще явно указать display

2022-02-15 18:51 UTC, merged