Сетки на гридах
htmlacademy-htmlcss/1083949-sedona-33 pull request #8
Opened 2022-02-17 09:34 UTC by olgabelka81

2022-02-17 18:28 UTC, saranchyev requested changes

2022-02-17 18:28 UTC, saranchyev commented on styles/style.css
>    margin-right: 72px;
Не стоит задавать так margin-ы, в угоду пиксель перфекту, с разницей всего в один пиксель. Макеты не бывают идеальными, зато мы можем сделать в верстке идеально одинаковые отступы с двух сторон. Поэтому будет лучше `margin: 0 72px;`

2022-02-17 18:28 UTC, saranchyev commented on styles/style.css
> +  display: grid;
https://skr.sh/sCYZrpLEOuy
Не пойму, для чего самой форме задан width: 200px, а внутри неё контейнер с гридом? Почему саму форму не сделать гридом?

2022-02-17 18:28 UTC, saranchyev commented on styles/style.css
> +  grid-template-columns: repeat(3, 358px);
https://skr.sh/sCYtXAKfjjI
У карточек гостиниц нужно убрать mergin, а отступы между карточками сделать через `gap`

2022-02-17 18:28 UTC, saranchyev commented on styles/style.css
> +  grid-column: 1/2;
Такие имена не содержательны, так как не понятно, чем `catalog-filter-1` отличается от `catalog-filter-2`. Не понятно что значит цифра. Нужно либо сделать имя более содержательным, например `catalog-filter-column-1`, либо вообще от них избавиться, так как колонки останутся рабочими и без указания им свойства `grid-column`

2022-02-18 12:50 UTC, olgabelka81 commented on styles/style.css
> +  display: grid;
Теперь и сама не пойму зачем...

2022-02-18 12:53 UTC, olgabelka81 commented on styles/style.css
> +  display: grid;
Теперь, и сама не пойму: зачем...

2022-02-19 07:07 UTC, merged