Декоративные элементы на главной странице
htmlacademy-htmlcss/1083949-sedona-33 pull request #9
Opened 2022-02-23 12:19 UTC by olgabelka81

2022-02-23 17:19 UTC, ego-o requested changes

2022-02-23 17:19 UTC, saranchyev commented on styles/style.css
> +  color: var(--color-light-brown);
https://skr.sh/vCe6kYG5Ctw?a
Такого происходить не должно. В стайлгайде сказано, что для фокуса никакие свои стили не добавляем, а оставляем браузерные. Везде, где нужно применять стили, там написано "Главная" - https://skr.sh/sCegTqnoDN0

При взаимодействии с интерактивными элементами они не должны менять своих размеров и сдвигаь друие части страницы, если только такое не предусмотрено в макете
https://up.htmlacademy.ru/htmlcss/33/criteries#TEST-08

2022-02-23 17:19 UTC, saranchyev commented on styles/style.css
> +}
https://skr.sh/sCe0tDq2DPj
Здесь при фокусе нужно отключить черную рамку (outline), так как для фокуса кнопки предусмотрены свои стили в макете.

Так же при фокусе элемент не должен менять свои размеры и сдвигать другие

2022-02-23 17:19 UTC, saranchyev commented on index.html
> +                <span class="counter-value">12</span>
https://skr.sh/sCeqTtO5rBu
Число в кругляшке нужно выровнять по его центру

2022-02-23 17:19 UTC, saranchyev commented on styles/style.css
> +  background-color: var(--color-light-grey);
https://skr.sh/sCeCswXALEN
Здесь так же не должно быть черной рамки при фокусе - https://skr.sh/sCehC376udq

Предусмотренны ли стили для ошибки?

2022-02-23 17:19 UTC, saranchyev commented on styles/style.css
> +  border: 3px solid var(--color-light-brown);
https://skr.sh/sCedEeFocYM
https://skr.sh/sCeoyS8qy0p
При фокусе на элементе не должно быть черной рамки. При нажатии на кнопку прозрачным должен быть только текст

2022-02-23 17:19 UTC, ego-o commented on styles/style.css
> +  border-radius: 10px;
https://skr.sh/vCeWiQMmwiV
При фокусе на элементах они не должны менять свои размеры. Не должно быть черной рамки

2022-02-23 17:19 UTC, ego-o commented on styles/style.css
> +  border: 3px solid var(--color-light-blue);
https://skr.sh/sCevLSPE1yD
Кликабельной должен быть только номер телефона. Клик по выделенным красным областям не должен приводить к фокусу на ссылке с телефоном. При фокусе не должно быть черной рамки

2022-02-23 17:19 UTC, ego-o commented on styles/style.css
> +  box-sizing: border-box;
https://skr.sh/sCenP4W79h8
При фокусе должен быть другой цвет у лого академии. Не должно быть черной рамки. Элемент не должен менять свои размеры, смещаться

2022-02-23 17:19 UTC, ego-o commented on catalog.html
> +                  <svg width="12" height="12" aria-hidden="true" focusable="false" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M6 .3 0 5.8V12h12V5.8L6 .3ZM11 11H1V6.2l5-4.5 5 4.5V11Z" fil
https://skr.sh/sCezgnzEn8k
Нужно поправить ПП

2022-02-23 17:28 UTC, olgabelka81 commented on styles/style.css
> +  color: var(--color-light-brown);
Я просто не поняла, что ничего менять не надо в фокусе в этом пункте.

2022-02-24 08:18 UTC, olgabelka81 commented on styles/style.css
> +}
Да, я видела, что она есть, но не знала , как отключить, думала дальше в курсе расскажут.

2022-02-24 16:53 UTC, ego-o commented on styles/style.css
> +}
https://skr.sh/vCfGvARZn0z?a
Синяя рамка при фокусе должна быть снаружи, а не внутри элемента

2022-02-24 17:02 UTC, ego-o commented on styles/style.css
> +  background-color: var(--color-light-grey);
https://skr.sh/sCfp6L1dUjt
https://skr.sh/sCfRqvaz1Ha

https://skr.sh/vCfLIh8JWpp?a
Не должно быть такого дерганья при наведении. Красная рамка так же не должна исчезать. И стоит добавить комментарий проверяющему наставнику, какой класс добавлять для состояния ошибки у инпута

2022-02-24 17:09 UTC, ego-o commented on styles/style.css
> +  border: 3px solid var(--color-light-brown);
https://skr.sh/sCf7SWUMP3V
Рамка фокуса должна быть снаружи

2022-02-24 17:13 UTC, ego-o commented
https://skr.sh/sCfyTl9yXOW
Рамка должна быть снаружи кнопки

2022-02-24 18:20 UTC, olgabelka81 commented on styles/style.css
> +  border: 3px solid var(--color-light-brown);
https://skr.sh/vCffrNH59ad

2022-02-24 18:23 UTC, olgabelka81 commented on styles/style.css
> +  border: 3px solid var(--color-light-brown);
![image](https://user-images.githubusercontent.com/80950029/155584281-a6704dbd-033d-4c7e-b880-4ba2f7de5db4.png)

2022-02-24 18:23 UTC, olgabelka81 commented on styles/style.css
> +  border: 3px solid var(--color-light-brown);
Так должно быть?

2022-02-25 16:25 UTC, merged